config/routes.rb
ShredList::Application.routes.draw do
  get "maps/index"
  devise_for :users
  root 'listings#index'

  resources :listings do
    collection do
      match 'search' => 'listings#search', via: [:get, :post], as: :search
    end
    resources :equipment
    resources :offers, only: [:new, :destroy, :create]
  end

  resources :equipment, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
  end

  resources :offers, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
    resources :replies, only: [:create, :destroy]
  end

  resources :users, only: [ :show ] do
    resources :listings, only: [:index]
    resources :offers, only: [:index]
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  validates_presence_of :title, :description, :state_id
  validates_numericality_of :asking_price,
    greater_than_or_equal_to: 0,
    allow_nil: true

  belongs_to :user,
    inverse_of: :listings
  belongs_to :state,
    inverse_of: :listings

  has_many :equipment,
    inverse_of: :listing,
    dependent: :destroy
  has_many :offers,
    inverse_of: :listing,
    dependent: :destroy

  def price_in_dollars
    "#{'%.2f' % (asking_price.to_d / 100) if asking_price}"
  end

  def price_in_dollars=(dollars)
    dollars = dollars.to_s.gsub(/[^0-9\.]+/, '')
    self.asking_price = dollars.to_d * 100 if dollars.present?
  end

  def owned_by?(viewer)
    if !viewer.nil?
      self.user_id == viewer.id
    end
  end

  def has_image?
    Picture.where(picturable_id: self.id).count > 0
  end

  def equipment_image
    pictures = equipment.sample.pictures
    pictures.sample.image_url(:thumb).to_s if pictures.count > 0
  end

  def state_name
    id = self.state_id
    State.find(id).name
  end

  def categories
    equipment.map{ |e| Category.find(e.category_id) }.uniq
  end

  def brands
    equipment.map{ |e| Brand.find(e.brand_id) }.uniq
  end

  def user_id
    self.user.id
  end

  def username
    user.username.capitalize
  end

  def currency_code
    currencies[state.name][0]
  end

  def currency_symbol
    currencies[state.name][1]
  end

  def currencies
    {
      "Alaska" => ['USD', '$'],
      "Alabama" => ['USD', '$'],
      "Arkansas" => ['USD', '$'],
      "American Samoa" => ['USD', '$'],
      "Arizona" => ['USD', '$'],
      "California" => ['USD', '$'],
      "Colorado" => ['USD', '$'],
      "Connecticut" => ['USD', '$'],
      "District of Columbia" => ['USD', '$'],
      "Delaware" => ['USD', '$'],
      "Florida" => ['USD', '$'],
      "Georgia" => ['USD', '$'],
      "Guam" => ['USD', '$'],
      "Hawaii" => ['USD', '$'],
      "Iowa" => ['USD', '$'],
      "Idaho" => ['USD', '$'],
      "Illinois" => ['USD', '$'],
      "Indiana" => ['USD', '$'],
      "Kansas" => ['USD', '$'],
      "Kentucky" => ['USD', '$'],
      "Louisiana" => ['USD', '$'],
      "Massachusetts" => ['USD', '$'],
      "Maryland" => ['USD', '$'],
      "Maine" => ['USD', '$'],
      "Michigan" => ['USD', '$'],
      "Minnesota" => ['USD', '$'],
      "Missouri" => ['USD', '$'],
      "Mississippi" => ['USD', '$'],
      "Montana" => ['USD', '$'],
      "North Carolina" => ['USD', '$'],
      "North Dakota" => ['USD', '$'],
      "Nebraska" => ['USD', '$'],
      "New Hampshire" => ['USD', '$'],
      "New Jersey" => ['USD', '$'],
      "New Mexico" => ['USD', '$'],
      "Nevada" => ['USD', '$'],
      "New York" => ['USD', '$'],
      "Ohio" => ['USD', '$'],
      "Oklahoma" => ['USD', '$'],
      "Oregon" => ['USD', '$'],
      "Pennsylvania" => ['USD', '$'],
      "Puerto Rico" => ['USD', '$'],
      "Rhode Island" => ['USD', '$'],
      "South Carolina" => ['USD', '$'],
      "South Dakota" => ['USD', '$'],
      "Tennessee" => ['USD', '$'],
      "Texas" => ['USD', '$'],
      "Utah" => ['USD', '$'],
      "Virginia" => ['USD', '$'],
      "Virgin Islands" => ['USD', '$'],
      "Vermont" => ['USD', '$'],
      "Washington" => ['USD', '$'],
      "Wisconsin" => ['USD', '$'],
      "West Virginia" => ['USD', '$'],
      "Wyoming" => ['USD', '$'],
      "Afghanistan" => ['AFN', '؋'],
      "Albania" => ['ALL', 'Lek'],
      "Algeria" => ['DZD', 'د.ج'],
      "Andorra" => ['EUR', '€'],
      "Angola" => ['AOA', 'Kz' ],
      "Anguilla" => ['XCD', '$'],
      "Antigua and Barbuda" => ['XCD', '$'],
      "Argentina" => ['ARS', '$'],
      "Armenia" => ['AMD', '&#1423;'],
      "Aruba" => ['AWG', 'ƒ'],
      "Australia" => ['AUD', '$'],
      "Austria" => ['EUR', '€'],
      "Azerbaijan" => ['AZN', 'ман'],
      "Bahamas" => ['BSD', '$'],
      "Bahrain" => ['BHD', '.د.ب '],
      "Bangladesh" => ['BDT', '৳'],
      "Barbados" => ['BBD', '$'],
      "Belarus" => ['BYR', 'p.'],
      "Belgium" => ['EUR', '€'],
      "Belize" => ['BZD', '$'],
      "Benin" => ['XOF', 'CFA'],
      "Bermuda" => ['BMD', '$'],
      "Bhutan" => ['BTN', 'Nu.'],
      "Bolivia" => ['BOB', '$b'],
      "Bosnia and Herzegowina" => ['BAM', 'KM'],
      "Botswana" => ['BWP', 'P'],
      "Bouvet Island" => ['EUR', '€'],
      "Brazil" => ['BRL', 'R$'],
      "British Indian Ocean Territory" => ['GBP', '£'],
      "Brunei Darussalam" => ['BND', '$'],
      "Bulgaria" => ['BGN', 'лв'],
      "Burkina Faso" => ['XOF', 'CFA'],
      "Burundi" => ['BIF','FBu'],
      "Cambodia" => ['',''],
      "Cameroon" => ['',''],
      "Canada" => ['',''],
      "Cape Verde" => ['',''],
      "Cayman Islands" => ['',''],
      "Central African Republic" => ['',''],
      "Chad" => ['',''],
      "Chile" => ['',''],
      "China" => ['',''],
      "Christmas Island" => ['',''],
      "Cocos (Keeling) Islands" => ['',''],
      "Colombia" => ['',''],
      "Comoros" => ['',''],
      "Congo" => ['',''],
      "Congo, the Democratic Republic of the" => ['',''],
      "Cook Islands" => ['',''],
      "Costa Rica" => ['',''],
      "Cote d'Ivoire" => ['',''],
      "Croatia (Hrvatska)" => ['',''],
      "Cuba" => ['',''],
      "Cyprus" => ['',''],
      "Czech Republic" => ['',''],
      "Denmark" => ['',''],
      "Djibouti" => ['',''],
      "Dominica" => ['',''],
      "Dominican Republic" => ['',''],
      "East Timor" => ['',''],
      "Ecuador" => ['',''],
      "Egypt" => ['',''],
      "El Salvador" => ['',''],
      "Equatorial Guinea" => ['',''],
      "Eritrea" => ['',''],
      "Estonia" => ['',''],
      "Ethiopia" => ['',''],
      "Falkland Islands (Malvinas)" => ['',''],
      "Faroe Islands" => ['',''],
      "Fiji" => ['',''],
      "Finland" => ['',''],
      "France" => ['',''],
      "France Metropolitan" => ['',''],
      "French Guiana" => ['',''],
      "French Polynesia" => ['',''],
      "French Southern Territories" => ['',''],
      "Gabon" => ['',''],
      "Gambia" => ['',''],
      "Georgia" => ['',''],
      "Germany" => ['',''],
      "Ghana" => ['',''],
      "Gibraltar" => ['',''],
      "Greece" => ['',''],
      "Greenland" => ['',''],
      "Grenada" => ['',''],
      "Guadeloupe" => ['',''],
      "Guam" => ['',''],
      "Guatemala" => ['',''],
      "Guinea" => ['',''],
      "Guinea-Bissau" => ['',''],
      "Guyana" => ['',''],
      "Haiti" => ['',''],
      "Heard and Mc Donald Islands" => ['',''],
      "Holy See (Vatican City State)" => ['',''],
      "Honduras" => ['',''],
      "Hong Kong" => ['',''],
      "Hungary" => ['',''],
      "Iceland" => ['',''],
      "India" => ['',''],
      "Indonesia" => ['',''],
      "Iran (Islamic Republic of)" => ['',''],
      "Iraq" => ['',''],
      "Ireland" => ['',''],
      "Israel" => ['',''],
      "Italy" => ['',''],
      "Jamaica" => ['',''],
      "Japan" => ['',''],
      "Jordan" => ['',''],
      "Kazakhstan" => ['',''],
      "Kenya" => ['',''],
      "Kiribati" => ['',''],
      "Korea" => ['',''],
      "Democratic People's Republic of" => ['',''],
      "Korea, Republic of" => ['',''],
      "Kuwait" => ['',''],
      "Kyrgyzstan" => ['',''],
      "Lao, People's Democratic Republic" => ['',''],
      "Latvia" => ['',''],
      "Lebanon" => ['',''],
      "Lesotho" => ['',''],
      "Liberia" => ['',''],
      "Libyan Arab Jamahiriya" => ['',''],
      "Liechtenstein" => ['',''],
      "Lithuania" => ['',''],
      "Luxembourg" => ['',''],
      "Macau" => ['',''],
      "Macedonia, The Former Yugoslav Republic of" => ['',''],
      "Madagascar" => ['',''],
      "Malawi" => ['',''],
      "Malaysia" => ['',''],
      "Maldives" => ['',''], 
      "Mali" => ['',''], 
      "Malta" => ['',''], 
      "Marshall Islands" => ['',''], 
      "Martinique" => ['',''], 
      "Mauritania" => ['',''], 
      "Mauritius" => ['',''], 
      "Mayotte" => ['',''], 
      "Mexico" => ['',''], 
      "Micronesia, Federated States of" => ['',''], 
      "Moldova, Republic of" => ['',''], 
      "Monaco" => ['',''], 
      "Mongolia" => ['',''], 
      "Montserrat" => ['',''], 
      "Morocco" => ['',''], 
      "Mozambique" => ['',''], 
      "Myanmar" => ['',''], 
      "Namibia" => ['',''], 
      "Nauru" => ['',''], 
      "Nepal" => ['',''], 
      "Netherlands" => ['',''], 
      "Netherlands Antilles" => ['',''], 
      "New Caledonia" => ['',''], 
      "New Zealand" => ['',''], 
      "Nicaragua" => ['',''], 
      "Niger" => ['',''], 
      "Nigeria" => ['',''], 
      "Niue" => ['',''], 
      "Norfolk Island" => ['',''], 
      "Northern Mariana Islands" => ['',''], 
      "Norway" => ['',''], 
      "Oman" => ['',''], 
      "Pakistan" => ['',''], 
      "Palau" => ['',''], 
      "Panama" => ['',''], 
      "Papua New Guinea" => ['',''], 
      "Paraguay" => ['',''], 
      "Peru" => ['',''], 
      "Philippines" => ['',''], 
      "Pitcairn" => ['',''], 
      "Poland" => ['',''], 
      "Portugal" => ['',''], 
      "Puerto Rico" => ['',''], 
      "Qatar" => ['',''], 
      "Reunion" => ['',''], 
      "Romania" => ['',''], 
      "Russian Federation" => ['',''], 
      "Rwanda" => ['',''], 
      "Saint Kitts and Nevis" => ['',''], 
      "Saint Lucia" => ['',''], 
      "Saint Vincent and the Grenadines" => ['',''], 
      "Samoa" => ['',''], 
      "San Marino" => ['',''], 
      "Sao Tome and Principe" => ['',''], 
      "Saudi Arabia" => ['',''], 
      "Senegal" => ['',''], 
      "Seychelles" => ['',''], 
      "Sierra Leone" => ['',''], 
      "Singapore" => ['',''], 
      "Slovakia (Slovak Republic)" => ['',''], 
      "Slovenia" => ['',''], 
      "Solomon Islands" => ['',''], 
      "Somalia" => ['',''], 
      "South Africa" => ['ZAR','R'], 
      "South Georgia and the South Sandwich Islands" => ['',''], 
      "Spain" => ['',''], 
      "Sri Lanka" => ['',''], 
      "St. Helena" => ['',''], 
      "St. Pierre and Miquelon" => ['',''], 
      "Sudan" => ['',''], 
      "Suriname" => ['',''], 

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  helper_method :listings

  def index
    @q = Listing.search(params[:q])
    @listings = @q.result
      .order('created_at DESC')
      .where(filter)
      .page(params[:page])
      .per(9)

  end

  def search
    index
    render :index
  end

  def show
    @listing = Listing.find(params[:id])
    @offer = Offer.new
    @offers = @listing.offers
    @picture = Picture.new
    @reply = Reply.new
    @equipments = @listing.equipment
  end

  def new
    @listing = Listing.new
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    if @listing.save
      redirect_to listing_path(@listing),
        flash: { success: "Your Shred Listing was posted!" }
    else
      render :new
    end
  end

  def update
    @listing = Listing.find(params[:id])

    if @listing.update(listing_params)
      redirect_to listing_path(@listing),
        falsh: { success: "Shred Listing was updated!" }
    else
      render :edit
    end
  end

  def destroy
    Listing.find(params[:id]).destroy
    redirect_to new_listing_path,
      notice: "Listing was successfully deleted."
  end

  private
  def listings
    @listings ||= Listing.all
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :trade, :state_id, :price_in_dollars, :asking_items)
  end

  def filter
    if params[:user_id]
      { user_id: User.where(username: params[:user_id]) }
    else
      {}
    end
  end
end

app/views/listings/_carousel.html.erb
<div id="carousel-generic" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
      <% @equipments.each_with_index do |equipment, index| %>
        <% equipment.pictures.each do |picture| %>
          <div class="item <%= index == 0 && equipment.pictures.first == picture ? 'active' : '' %>">
            <%= image_tag picture.image_url.to_s %>
            <div class="carousel-caption">
              <h3><%= equipment.brand.name %></h3>
              <p><%= @listing.currency_symbol %> <%= equipment.price_in_dollars %></p>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
  <a  class="left carousel-control" href="#carousel-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/listings/_equipments.html.erb
<table class="table table-striped" >
  <thead>
    <tr>
      <th>Brand</th>
      <th>Category</th>
      <th>Original Price</th>
      <th>Riding Style</th>
      <% if @listing.owned_by?(current_user) %>
        <th></th>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @listing.equipment.each do |equipment| %>
    <tr>
    <td><%= equipment.brand.try(:name) %></td>
    <td><%= equipment.category.try(:name) %></td>
    <td><%= @listing.currency_symbol %> <%= equipment.price_in_dollars %> (<%= @listing.currency_code %>)</td>
    <td><%= equipment.riding_style.try(:name) %></td>
        <% if @listing.owned_by?(current_user) %>
          <td><%= link_to 'Show', listing_equipment_path(@listing, equipment), class: 'btn btn-default btn-xs' %></td>
          <td><%= link_to 'Edit', edit_listing_equipment_path(@listing, equipment), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Delete', listing_equipment_path(@listing, equipment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/listings/_form.html.erb
<div class="wrapper">
  <%= simple_form_for(@listing, html: { class: "form-vertical" }) do |f| %>
    <%= f.input :title, autofocus: true %>
    <%= f.input :description, as: :text %>
    <%= f.collection_radio_buttons :trade, [[false, 'Sell'], [true, 'Trade']], :first, :last, item_wrapper_class: 'radio-inline' %>
    <%= f.association :state, collection: State.all %>
    <%= f.input :price_in_dollars, label: "Asking Price" %>
    <%= f.input :asking_items, label: "Asking Items", as: :text  %>
    <%= f.submit @listing.new_record? ? "Add Listing" : "Update Listing", class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/listings/_search_form.html.erb
<%= search_form_for @q, url: search_listings_path, html: { method: :post } do |f| %>
  <li>
  <%= f.label :trade_eq, "Sell or Trade" %><br>
  <%= f.select :trade_eq, options_for_select([["Sell",false], ["Trade",true]]), include_blank: true %>
  </li>
  <li>
  <%= f.label :title_cont, "Title" %><br>
  <%= f.text_field :title_cont %>
  </li>
  <li>
  <%= f.label :state_name_cont, "Location" %><br>
  <%= f.select :state_id_eq, options_from_collection_for_select(State.all, "id", "name", @q.state_id_eq), include_blank: true %>
  </li>
  <li>
  <%= f.label :equipment_brand_id_eq, "Brand" %><br>
  <%= f.select :equipment_brand_id_eq, options_from_collection_for_select(Brand.all, "id", "name", @q.equipment_brand_id_eq), include_blank: true %>
  </li>
  <li>
  <%= f.label :equipment_category_id_eq, "Category" %><br>
  <%= f.select :equipment_category_id_eq, options_from_collection_for_select(Category.all, "id", "name", @q.equipment_category_id_eq), include_blank: true %>
  </li>
  <br>
  <li>
  <%= f.submit "Find", class: 'btn btn-success' %>
  </li>
<% end %>

app/views/listings/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class='text-center'>Editing Listing</h1>
  <%= render 'form' %>
</div>

<%= content_for :extra_footer do %>
  <script>
    $(document).ready(function() {
      <% unless @listing.trade %>
        $('.listing_asking_items').toggle();
      <% end %>
      $("[name='listing[trade]']").change(function(){
        $('.listing_asking_items').toggle();
      });
    });
  </script>
<% end %>

app/views/listings/index.html.erb
<div class="row">
  <h1 class="text-center">Find Your Shred</h1>
  <% if listings.present? %>
    <% listings.each do |listing| %>
      <div class="col-6 col-sm-6 col-md-5 col-lg-4">
        <div class="thumbnail listing-show">
          <%= image_tag (listing.equipment.present? && !listing.equipment_image.nil?) ? listing.equipment_image : 'fallback/default.jpg' %>
          <div class="caption">
            <h3 class="title"><%= listing.try(:title) %></h3>
            <div class="description"><p><%= listing.try(:description) %></p></div>
            <p class="detail"><strong><%= link_to listing.username, user_path(listing.user) %></strong> from <strong><%= listing.state_name %></strong> is <strong><%= listing.trade ? "trading" : "selling" %></strong><br>
            <strong>Category</strong>:
            <% listing.categories.each do |category| %>
              <%= category.name %><%= "," unless category == listing.categories.last %>
            <% end %><br>
            <strong>Brand</strong>:
            <% listing.brands.each do |brand| %>
              <%= brand.name %><%= "," unless brand == listing.brands.last %>
            <% end %></p>
            <%= link_to 'Details', listing_path(listing), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="alert alert-warning col-md-8 col-md-offset-2">
      <h1 class="text-center">There are no listings.</h1>
      <h3 class="text-center"><%= link_to 'Make One!', user_signed_in? ? new_listing_path : new_user_registration_path %></h3>
    </div>
  <% end %>
</div>

<div class="col-md-7 col-md-offset-4">
  <%= paginate @listings, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-sm pagination-center' %>
</div>

app/views/listings/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class='text-center'>Create New Listing</h1>
  <div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h3>Sell or trade your equipment(s) in 3 easy steps!</h3>
    <ol class="info">
      <li>Add details of the listing.</li>
      <li>Add details of your equipment(s) on the next page.</li>
      <li>Add at least one picture to each equipment.</li>
    </ol>
  </div>
  <%= render 'form' %>
</div>

<%= content_for :extra_footer do %>
  <script>
    $(document).ready(function() {
      $('.listing_asking_items').toggle();
      $("[name='listing[trade]']").change(function(){
        $('.listing_asking_items').toggle();
      });
    });
  </script>
<% end %>

app/views/listings/show.html.erb
<%
  meta title: @listing.title + ' | Shred List',
       description: @listing.description
%>

<div class="post">
  <p class='listings-nav'><% if user_signed_in? && @listing.owned_by?(current_user) %>
    <%= link_to 'My Listings', user_listings_path(current_user) %> | 
  <% end %>
  <%= link_to 'All Listings', listings_path %></p>
  <div class="row ind-listing">
    <div class="col-md-7">
      <h1><%= @listing.title %><br><small> by <%= link_to @listing.user.username, user_path(@listing.user)%> on <%= @listing.created_at.strftime("%m/%e/%y") %></small></h1>
        <p><strong>Description:</strong> <%= @listing.description %></p>
        <% if !@listing.asking_price.nil? %>
          <p><strong>Asking price:</strong> <%= @listing.currency_symbol %> <%= @listing.price_in_dollars %> (<%= @listing.currency_code %>)</p>
        <% end %>
        <% if !@listing.asking_items.nil? && @listing.trade%>
          <p><strong>Asking items:</strong> <%= @listing.asking_items %></p>
        <% end %>
        <p><strong>Location:</strong> <%= @listing.state.try(:name) %></p>

        <%= render 'listings/equipments' %> 

        <% if @listing.owned_by?(current_user) %>
          <%= link_to 'Edit Listing', edit_listing_path(@listing),  class: 'btn btn-info' %>
          <%= link_to 'New Equipment', new_listing_equipment_path(@listing), class: 'btn btn-info' %>
          <%= link_to 'Delete Listing', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link' %><br>
        <% end %>
      </div>

      <div class="col-md-5">
        <%= render 'listings/carousel' %>
      </div>
    </div>
  </div>

  <p><%= link_to 'Make An Offer', user_signed_in? ? '#' : new_user_registration_path, id: 'make_offer', class: "btn btn-primary" %></p>

  <div class="offers">
    <%= render 'offers/form' %>
  </div>

  <%= render 'offers/offers' %>

  <%= content_for :extra_footer do %>
    <script>
      $(document).ready(function() {
        $('#new_offer').toggle();
        $('#make_offer').on("click", function(e) {
          $('#new_offer').toggle();
        });
        $('#new_reply').toggle();
        $('#make_reply').on("click", function(e) {
          $('#new_reply').toggle();
        });
      });
    </script>
  <% end %>