config/routes.rb
ShredList::Application.routes.draw do
  get "maps/index"
  devise_for :users
  root 'listings#index'

  resources :listings do
    collection do
      match 'search' => 'listings#search', via: [:get, :post], as: :search
    end
    resources :equipment
    resources :offers, only: [:new, :destroy, :create]
  end

  resources :equipment, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
  end

  resources :offers, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
    resources :replies, only: [:create, :destroy]
  end

  resources :users, only: [ :show ] do
    resources :listings, only: [:index]
    resources :offers, only: [:index]
  end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  validates_presence_of :original_price, :category_id, :brand_id
  validates_numericality_of :original_price,
    greater_than_or_equal_to: 0
  belongs_to :brand,
    inverse_of: :equipment
  belongs_to :category,
    inverse_of: :equipment
  belongs_to :riding_style,
    inverse_of: :equipment
  belongs_to :listing,
    inverse_of: :equipment
  has_many :pictures,
    as: :picturable,
    dependent: :destroy

  def price_in_dollars
    "#{'%.2f' % (original_price.to_d / 100) if original_price}"
  end

  def price_in_dollars=(dollars)
    dollars = dollars.to_s.gsub(/[^0-9\.]+/, '')
    self.original_price = dollars.to_d * 100 if dollars.present?
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_filter :listing, :authenticate_user!

  def new
    @equipment = listing.equipment.new
  end

  def show
    @equipment = listing.equipment.find(params[:id])
    @picture = @equipment.pictures.new
  end

  def edit
    @equipment = listing.equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])

    if @equipment.update(equipment_params)
      redirect_to listing,
        flash: { success: "This equipment need at least a picturefor it to go live." }
    else
      render :edit
    end
  end

  def create
    @equipment = listing.equipment.new(equipment_params)

    if @equipment.save
      redirect_to listing_equipment_path(@listing, @equipment),
        flash: { success: "You added an equipment!" }
    else
      render :new
    end
  end

  def destroy
    listing.equipment.find(params[:id]).destroy
    redirect_to listing,
      notice: "Equipment was successfully deleted."
  end

  private
  def listing
    @listing ||= Listing.find(params[:listing_id])
  end

  def equipment_params
    params.require(:equipment).permit(:brand_id, :category_id, :riding_style_id, :price_in_dollars)
  end
end

app/views/equipment/_equipment.html.erb
<% @equipment.each do |e| %>
  <strong>Brand:</strong> <%= e.brand.try(:name) %><br>
  <strong>Category: </strong> <%= e.category.try(:name) %><br>
  <strong>Riding Style: </strong> <% e.riding_style.try(:name)  %><br>
  <strong>Original Price: $</strong><%= e.price_in_dollars %><br>
  <hr>
<% end %>

app/views/equipment/_form.html.erb
<div class="wrapper">
<%= simple_form_for([@listing, @equipment], html: { class: 'form-vertical' }) do |f| %>
  <%= f.association :brand, collection: Brand.all %>
  <%= f.association :category, collection: Category.all %>
  <%= f.association :riding_style, collection: RidingStyle.all %>
  <%= f.input :price_in_dollars, label: 'Original Price' %>
  <%= f.submit @equipment.new_record? ? "Create Equipment" : "Update Equipment", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/equipment/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit Equipment</h1>

  <%= render 'form' %>

  <%= link_to 'Back to listing',  listing_path(@listing) %>
</div>

app/views/equipment/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= link_to 'Back to listing', listing_path(@listing) %>
  <h1>New Equipment</h1>

  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4>Add pictures of this equipment on the next page</h4>
  </div>

  <%= render 'form' %>
</div>

app/views/equipment/show.html.erb
<% if @equipment.pictures.first.id.present? %>
  <%= link_to 'Back to listing', listing_path(@listing) %>
<% else %>
  <div class="alert alert-warning"><h1>You must upload at least 1 picture for this equipment!</h1></div>
<% end %>
<div class="row ind-listing">

  <h1>Equipment Info</h1>

  <div class="col-md-4">
    <strong>Brand:</strong> <%= @equipment.brand.try(:name) %><br>
    <strong>Category:</strong> <%= @equipment.category.try(:name) %><br>
    <strong>Riding Style:</strong> <% @equipment.riding_style.try(:name)  %><br>
    <strong>Original Price:</strong> $<%= @equipment.price_in_dollars %><br>

    <div class="add_photo">
      <%= simple_form_for([@equipment, @picture], html: { multipart: true }) do |f| %>
        <%= f.input :image, as: :file %>
        <%= f.submit "Add Picture", class: 'btn btn-primary' %>
      <% end %>
    </div>

  </div>

  <div class="col-md-8">
    <% @equipment.pictures.each do |picture| %>
      <% if picture.id %>
        <div class="col-xs-6 col-md-4">
          <a href="#" class="thumbnail">
            <%= image_tag picture.image_url(:thumb).to_s %>
            <%= link_to 'Delete', [@equipment, picture], method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link' %>
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
</div>