config/routes.rb
ShredList::Application.routes.draw do
  get "maps/index"
  devise_for :users
  root 'listings#index'

  resources :listings do
    collection do
      match 'search' => 'listings#search', via: [:get, :post], as: :search
    end
    resources :equipment
    resources :offers, only: [:new, :destroy, :create]
  end

  resources :equipment, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
  end

  resources :offers, only: [] do
    resources :pictures, only: [:new, :destroy, :create]
    resources :replies, only: [:create, :destroy]
  end

  resources :users, only: [ :show ] do
    resources :listings, only: [:index]
    resources :offers, only: [:index]
  end

end

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom"  role="navigation">
<div class="container">
  <p class="navbar-text">&copy;Shred List <%= Time.now.year %> | Get in touch <a href="https://twitter.com/intent/tweet?screen_name=ParindaDarden" class="twitter-mention-button" data-related="ParindaDarden">Tweet to @ParindaDarden</a></p>
</div>
</nav>

<%= content_for :extra_footer do %>
  <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :success ? "success" : (name == :notice ? "info" : "danger") %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Shred List', root_path, class: 'navbar-brand' %>
  </div>
<!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to 'Map', maps_index_path %></li>

      <% if current_page?(root_path) || current_page?(listings_path) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Search</a>
          <ul class="dropdown-menu">
            <%= render 'listings/search_form' %>
          </ul>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Sell | Trade', new_listing_path %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="greeting">Hello, <%= current_user.first_name.capitalize %>!<b class="caret"></b></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to 'My Listings', user_listings_path(current_user) %></li>
          <li><%= link_to 'My Offers', user_offers_path(current_user) %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to 'Sell | Trade', new_user_registration_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>